name: Michael
favicon: null
layout_spectrum: 0.2852
typography_spectrum: 0.15435884543694556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5142094-10
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.75
  lightness: 0.5283182826824486
  saturation: 0.7065728716552258
  rhythmicContrast: 0.7493707172106951
purpose: []
